export enum Plan {
  TIER_ONE = 'TIER_ONE',
  TIER_TWO = 'TIER_TWO',
  TIER_THREE = 'TIER_THREE',
  TIER_FOUR = 'TIER_FOUR',
}

export enum Stage {
  FINAL = 'FINAL',
  THIRD_PLACE = 'THIRD_PLACE',
  SEMI_FINALS = 'SEMI_FINALS',
  QUARTER_FINALS = 'QUARTER_FINALS',
  LAST_16 = 'LAST_16',
  LAST_32 = 'LAST_32',
  LAST_64 = 'LAST_64',
  ROUND_4 = 'ROUND_4',
  ROUND_3 = 'ROUND_3',
  ROUND_2 = 'ROUND_2',
  ROUND_1 = 'ROUND_1',
  GROUP_STAGE = 'GROUP_STAGE',
  PRELIMINARY_ROUND = 'PRELIMINARY_ROUND',
  QUALIFICATION = 'QUALIFICATION',
  QUALIFICATION_ROUND_1 = 'QUALIFICATION_ROUND_1',
  QUALIFICATION_ROUND_2 = 'QUALIFICATION_ROUND_2',
  QUALIFICATION_ROUND_3 = 'QUALIFICATION_ROUND_3',
  PLAYOFF_ROUND_1 = 'PLAYOFF_ROUND_1',
  PLAYOFF_ROUND_2 = 'PLAYOFF_ROUND_2',
  PLAYOFFS = 'PLAYOFFS',
  REGULAR_SEASON = 'REGULAR_SEASON',
  CLAUSURA = 'CLAUSURA',
  APERTURA = 'APERTURA',
  CHAMPIONSHIP = 'CHAMPIONSHIP',
  RELEGATION = 'RELEGATION',
  RELEGATION_ROUND = 'RELEGATION_ROUND',
}

export enum Status {
  CANCELLED = 'CANCELLED',
  FINISHED = 'FINISHED',
  IN_PLAY = 'IN_PLAY',
  LIVE = 'LIVE',
  PAUSED = 'PAUSED',
  POSTPONED = 'POSTPONED',
  SCHEDULED = 'SCHEDULED',
  SUSPENDED = 'SUSPENDED',
}

export enum Venue {
  HOME = 'HOME',
  AWAY = 'AWAY',
}
