name: Pages

on:
  push:
    branches:
      - master

jobs:
  pages:
    name: Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install Docsify
        run: yarn global add docsify
      - name: Build Production
        run: yarn docsify
      - name: Deploy Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          token: ${{ secrets.GHP_TOKEN }}
          branch: gh-pages
          folder: docs
          clean: true
